Dynegy/src/objects/DASR_Request__c.object
<CustomObject>
    <fields>
        <fullName>Accepted__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Accepted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Change_Effective_Date__c</fullName>
        <label>Change Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DASR_Type__c</fullName>
        <label>DASR Type</label>
        <picklist>
            <picklistValues>
                <fullName>GAAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAAH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GAAR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Drop_Reason_Code__c</fullName>
        <label>Drop Reason Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dynegy_Initiated__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Dynegy Initiated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Integration_Status__c</fullName>
        <label>Integration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In-Process</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Validation Failed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting For Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manually Fulfilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TEST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LDC_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LDC Account</label>
        <referenceTo>LDC_Account__c</referenceTo>
        <relationshipName>DASRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_GAAD__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is created to Check whether the DASR is most recent one or not</description>
        <label>Most Recent DASR</label>
        <type>Checkbox</type>
    </fields>
    <label>DASR Request</label>
    <nameField>
        <displayFormat>DASR-{0}</displayFormat>
        <label>DASR</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DASR Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Dynegy/src/objects/LDC_Account__c.object
<CustomObject>
    <fields>
        <fullName>LDC_Account_Status__c</fullName>
        <description>Status Values for overall LDC Account</description>
        <inlineHelpText>Status of the LDC Account</inlineHelpText>
        <label>LDC Account Status</label>
        <picklist>
            <picklistValues>
                <fullName>NEW_ACCOUNT</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>ACTIVE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FINAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING_FINAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PENDING_ENROLLMENT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>REJECTED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DRAFT</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>LDC_Start_Date__c</fullName>
        <description>Start Date of the LDC</description>
        <label>LDC Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Service_Territory__c</fullName>
        <globalPicklist>Service_Territory</globalPicklist>
        <label>Service Territory</label>
        <type>Picklist</type>
    </fields>
    <label>LDC Account</label>
    <nameField>
        <label>LDC Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LDC Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Dynegy/src/classes/DASRGAADBatch.cls
global class DASRGAADBatch implements Database.Batchable < sObject > {

    global DASRGAADBatch() {

    }
    String q;
    /**
     * @description gets invoked when the batch job starts
     * @param context contains the job ID
     * @returns the record set as a QueryLocator object that will be batched for execution
     */
    global Database.QueryLocator start(Database.BatchableContext context) {
        list<DASR_GAAD_Batch__c> dropJob = dasr_gaad_batch__C.getall().values();
        set<string> droptype= new set<string>();
        for(DASR_GAAD_Batch__c type:dropJob){
            if(datetime.now().time().hour() == Integer.valueof(type.time__c) && datetime.now().time().minute() >= Integer.valueof(type.minute__c) && datetime.now().time().minute() <= Integer.valueof(type.minute1__c )){  
                system.debug('*******time in Custom Setting*******' +type.time__c);
                droptype.add(type.DASR_Type__c);
            }
        }
        if(droptype.contains('EC'))
           q = 'select id,ldc_account__r.ldc_account_status__C,ldc_account__r.ldc_start_date__C,drop_reason_code__c From DASR_Request__c  where (Dynegy_Initiated__c = False OR Accepted__c = true) AND Integration_Status__c = \'Complete\' AND Change_Effective_Date__c != null and Dasr_type__c = \'GAAD\'  and Most_recent_gaad__C = true and (drop_transaction_type__C = \'EC\' OR (drop_reason_code__c = \'EB3\' AND ldc_account__r.service_territory__C like \'%OH%\')) and lastmodifieddate = today';
        else
            q = 'select id,ldc_account__r.ldc_account_status__C From DASR_Request__c  where (Dynegy_Initiated__c = False OR Accepted__c = true) AND Integration_Status__c = \'Complete\' AND Change_Effective_Date__c != null and Change_Effective_Date__c <= Today and Dasr_type__c = \'GAAD\' and (drop_transaction_type__C = \'DR\' AND drop_reason_code__c != \'EB3\') and Most_recent_gaad__C = true and lastmodifieddate >='+label.DASR_GAAD_Date;//AND (NOT ldc_account__r.service_territory__C like \'%OH%\'))

        system.debug('>>>>>>>>>>>>>>>>>*******' + q);

        return Database.getQueryLocator(q);
    }

    /**
     * @description gets invoked when the batch job executes and operates on one batch of records. Contains or calls the main execution logic for the batch job.
     * @param context contains the job ID
     * @param scope contains the batch of records to process.
     */
    global void execute(Database.BatchableContext context, List<DASR_Request__c> scope) {


        List<Id> idList = new List<Id> ();
        list<DASR_Request__c> lDASR = (list<DASR_Request__c>) scope;
        list<DASR_Request__c> updateDASRList = new list<DASR_Request__c>();
        system.debug('>>>>>>>>>>>>>>>>>*******' + scope);
        
        for (DASR_Request__C dasrRequest : lDASR) {
            if(dasrRequest.ldc_account__r.ldc_account_status__C.equalsignorecase('FINAL')){
                dasrRequest.Most_recent_gaad__C = false;
                updateDASRList.add(dasrRequest);
            }
            else{
                idList.add(dasrRequest.Id);
                dasrRequest.Most_recent_gaad__C = false;
                updateDASRList.add(dasrRequest);
            }
        }
        system.debug('>>>>>>>>>>>>>>>>>*******' + idList);
        Flow_EndContractLDC.TerminateActiveContractsByDASR(idList);
        system.debug('>>>>>>>>>>>>>>>>>*******' +updateDASRList);
        if (!updateDASRList.isempty()) update updateDASRList;

    }

    /**
     * @description gets invoked when the batch job finishes. Place any clean up code in this method.
     * @param context contains the job ID
     */
    global void finish(Database.BatchableContext context) {

    }


}